### PR TITLE
[tex] Fix glance-scrubber BadStoreConfiguration error, (bnc#930739)

### PR DESCRIPTION
**Pull request by mjura**
(cherry picked from commit 0db8f9a775556a06d11b663d342b792e81f589e1)
(cherry picked from commit 82e90702d06a252f0be362a2a647d33394eeacd5)

According to bug description we would like to have also this fix in SC5

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by dirkmueller** [comment]
@mjura looks like this was not cherry-picked from the last revision, the "cherry-picked from" lines should be 0db8f9a and 82e9070. can you please cherry-pick the version that went into master?

-1

**Comment by mjura** [comment]
@dirkmueller Thank you, I fixed comments

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
